//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertMService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CERTIFICATE_MANAGEMENTEntities : DbContext
    {
        public CERTIFICATE_MANAGEMENTEntities()
            : base("name=CERTIFICATE_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<CERTIFICATE> CERTIFICATE { get; set; }
        public virtual DbSet<CLASS> CLASS { get; set; }
        public virtual DbSet<SCOREBOARD> SCOREBOARD { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATE { get; set; }
    }
}
