//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertMService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE
    {
        public string Name { get; set; }
        public string FrontLink { get; set; }
        public string EndLink { get; set; }
    }
}
