//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertMService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        public CLASS()
        {
            this.CERTIFICATE = new HashSet<CERTIFICATE>();
        }
    
        public string ClassNo { get; set; }
        public string Link { get; set; }
    
        public virtual ICollection<CERTIFICATE> CERTIFICATE { get; set; }
    }
}
